"""add exit_reason to trade_history

Revision ID: 22b454287b33
Revises: 0011
Create Date: 2026-07-31 22:10:17.547019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b454287b33'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_fills', sa.Column('exit_reason', sa.String(length=40), nullable=True))
    op.add_column('pending_fills', sa.Column('exit_trigger', sa.String(length=40), nullable=True))
    op.add_column('trade_history', sa.Column('exit_reason', sa.String(length=40), nullable=True))
    op.add_column('trade_history', sa.Column('exit_trigger', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_history', 'exit_trigger')
    op.drop_column('trade_history', 'exit_reason')
    op.drop_column('pending_fills', 'exit_trigger')
    op.drop_column('pending_fills', 'exit_reason')
    # ### end Alembic commands ###
